spring:
  application:
    name: calma-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword

server:
  address: 192.168.1.200
  port: 8080
